<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex Sans KR&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="css/main.css">
    <title>ProState Bank</title>
</head>
<body>
<header>
    <div id="logo-button">
        <a href="index.php" class="logo">Pro State Bank</a>
    </div>
    <div id="buttons">
        <a href="profile.php" class="button">Profile</a>
        <a href="cards.php" class="button">Cards</a>
        <a href="money_transfer.php" class="button">Money transfer</a>
        <a href="history.php" class="button">History</a>
        <a href="fiscles.php" class="button">Fiscleees!</a>
        <!-- no stress armand, safixos -->
        <a href="login.php" class="log">Sign In</a>
        <a href="logout.php" class="log">Sign Out</a>
    </div>
</header>