<footer>
    <a href="/">© ProState Bank</a>
    <?php
    if(!empty($_SESSION["logged"])) {
        echo "<a href='/profile'>Profile</a>";
        echo "<a href='/accounts'>Accounts</a>";
        echo "<a href='/money_transfer'>Transfer</a>";
        echo "<a href='/history'>History</a>";
        echo "<a href='/request'>Sūtīt ziņojumu</a>";
    }
    ?>
    <a href="/faq">FAQ</a>
</footer>
</body>
</html>